import type { Product } from "./types";

export const products: Product[] = [
  {
    id: "1",
    name: "Pro Business Laptop",
    description:
      "High performance laptop designed for professional multitasking and business applications.",
    price: 999.99,
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=500",
    category: "Laptop",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "2",
    name: "MacBook Air",
    description:
      "Lightweight and powerful notebook featuring Apple's M1 chip for everyday productivity.",
    price: 1199.99,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500",
    category: "MacBook",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "3",
    name: "Gaming Beast PC",
    description:
      "Ultimate gaming desktop with a top-tier GPU and CPU for an immersive gaming experience.",
    price: 1999.99,
    image: "https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=500",
    category: "Gaming PC",
    rating: 4.9,
    inStock: true,
  },
  {
    id: "4",
    name: "Ergo Standing Desk",
    description:
      "Adjustable standing desk designed to improve posture and reduce the risks of prolonged sitting.",
    price: 399.99,
    image: "https://images.unsplash.com/photo-1622126755582-16754165dce8?w=500",
    category: "Standing Desk",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "5",
    name: "UltraComfort Ergonomic Chair",
    description:
      "Ergonomic office chair with customizable lumbar support for optimal comfort during long hours.",
    price: 249.99,
    image: "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=500",
    category: "Ergonomic Chair",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "6",
    name: "Precision Wireless Mouse",
    description:
      "High-precision wireless mouse with customizable buttons and an ergonomic design for comfort.",
    price: 49.99,
    image: "https://images.unsplash.com/photo-1586349906319-48d20e9d17e5?w=500",
    category: "Mouse",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "7",
    name: "Advanced Workstation Laptop",
    description:
      "A powerful workstation laptop built for intensive creative tasks and complex workflows.",
    price: 1499.99,
    image: "https://images.unsplash.com/photo-1522199755839-a2bacb67c546?w=500",
    category: "Laptop",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "8",
    name: "MacBook Pro",
    description:
      "High-performance MacBook Pro designed for creative professionals with demanding applications.",
    price: 2399.99,
    image: "https://images.unsplash.com/photo-1518448828347-28e2cf0d6e28?w=500",
    category: "MacBook",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "9",
    name: "Elite Gaming Monitor",
    description:
      "High-refresh rate gaming monitor that delivers smooth visuals and vibrant colors for competitive gaming.",
    price: 349.99,
    image: "https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=500",
    category: "Monitor",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "10",
    name: "Ergo Desk Lamp",
    description:
      "Adjustable LED desk lamp with multiple brightness levels to reduce eye strain during long work sessions.",
    price: 79.99,
    image: "https://images.unsplash.com/photo-1523380262778-076eb862d38f?w=500",
    category: "Office Accessory",
    rating: 4.4,
    inStock: true,
  },

  // Laptops
  {
    id: "11",
    name: "Pro Business Laptop",
    description:
      "High performance laptop designed for multitasking and business applications.",
    price: 999.99,
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=500",
    category: "Laptop",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "12",
    name: "Ultra Slim Laptop",
    description:
      "Lightweight laptop with a sleek design and long battery life.",
    price: 899.99,
    image: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=500",
    category: "Laptop",
    rating: 4.3,
    inStock: true,
  },
  {
    id: "13",
    name: "Performance Laptop X",
    description: "A powerful machine built for professionals and gamers alike.",
    price: 1299.99,
    image: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=500",
    category: "Laptop",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "14",
    name: "Budget Laptop 101",
    description:
      "Affordable laptop perfect for everyday tasks and basic computing.",
    price: 499.99,
    image: "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=500",
    category: "Laptop",
    rating: 4.0,
    inStock: true,
  },
  {
    id: "15",
    name: "Convertible 2-in-1 Laptop",
    description:
      "Versatile laptop with touchscreen and 360-degree hinge functionality.",
    price: 1099.99,
    image: "https://images.unsplash.com/photo-1544731612-de7f96afe55f?w=500",
    category: "Laptop",
    rating: 4.4,
    inStock: true,
  },
  {
    id: "16",
    name: "Enterprise Ultrabook",
    description:
      "Premium ultrabook optimized for business security and performance.",
    price: 1399.99,
    image: "https://images.unsplash.com/photo-1504707748692-419802cf939d?w=500",
    category: "Laptop",
    rating: 4.6,
    inStock: true,
  },
  // MacBooks
  {
    id: "17",
    name: "MacBook Air",
    description: "Lightweight and efficient notebook powered by Apple M1 chip.",
    price: 1199.99,
    image: "https://images.unsplash.com/photo-1625766763788-95dcce9bf5ac?w=500",
    category: "MacBook",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "18",
    name: 'MacBook Pro 13"',
    description: "Compact yet powerful MacBook Pro with a retina display.",
    price: 1699.99,
    image: "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=500",
    category: "MacBook",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "19",
    name: 'MacBook Pro 16"',
    description:
      "A top-tier MacBook Pro delivering exceptional performance for professionals.",
    price: 2399.99,
    image: "https://images.unsplash.com/photo-1717865499857-ec35ce6e65fa?w=500",
    category: "MacBook",
    rating: 4.9,
    inStock: true,
  },
  {
    id: "20",
    name: "MacBook Air M2",
    description:
      "Latest MacBook Air with upgraded performance and battery life.",
    price: 1299.99,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500",
    category: "MacBook",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "21",
    name: "Refurbished MacBook Pro",
    description:
      "Certified refurbished MacBook Pro with premium specs at a great value.",
    price: 1999.99,
    image: "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=500",
    category: "MacBook",
    rating: 4.5,
    inStock: true,
  },
  // Gaming PCs
  {
    id: "22",
    name: "Gaming Beast PC",
    description:
      "High-end gaming desktop with a top-tier GPU and CPU for immersive gameplay.",
    price: 1999.99,
    image: "https://images.unsplash.com/photo-1572314493295-09c6d5ec3cdf?w=500",
    category: "Gaming PC",
    rating: 4.9,
    inStock: true,
  },
  {
    id: "23",
    name: "Compact Gaming PC",
    description:
      "Small form factor gaming PC that delivers high performance without taking up much space.",
    price: 1499.99,
    image: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=500",
    category: "Gaming PC",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "24",
    name: "VR Ready Gaming PC",
    description:
      "Optimized for virtual reality experiences with advanced cooling and performance.",
    price: 2199.99,
    image: "https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=500",
    category: "Gaming PC",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "25",
    name: "Overclocked Gaming PC",
    description:
      "Performance-tuned gaming desktop designed for extreme gaming and streaming.",
    price: 2499.99,
    image: "https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=500",
    category: "Gaming PC",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "26",
    name: "Budget Gaming PC",
    description:
      "Affordable gaming desktop offering solid performance for esports and casual gaming.",
    price: 1199.99,
    image: "https://images.unsplash.com/photo-1660855551740-4474188debdb?w=500",
    category: "Gaming PC",
    rating: 4.3,
    inStock: true,
  },
  // Standing Desks
  {
    id: "27",
    name: "Ergo Standing Desk",
    description:
      "Adjustable standing desk designed to improve posture and productivity.",
    price: 399.99,
    image: "https://images.unsplash.com/photo-1623679072629-3aaa0192a391?w=500",
    category: "Standing Desk",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "28",
    name: "Smart Height Adjustable Desk",
    description:
      "Standing desk with memory presets and smooth electronic adjustment.",
    price: 499.99,
    image: "https://images.unsplash.com/photo-1622131815452-cc00d8d89f02?w=500",
    category: "Standing Desk",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "29",
    name: "Compact Standing Desk",
    description:
      "Perfect for home offices; offers easy adjustment in a compact form.",
    price: 359.99,
    image: "https://images.unsplash.com/photo-1632923946204-a7bc5c848ca6?w=500",
    category: "Standing Desk",
    rating: 4.4,
    inStock: true,
  },
  {
    id: "30",
    name: "ErgoPro Standing Desk",
    description:
      "High-capacity standing desk with customizable settings for optimal comfort.",
    price: 449.99,
    image: "https://images.unsplash.com/photo-1699831112447-9c8c803f584b?w=500",
    category: "Standing Desk",
    rating: 4.5,
    inStock: true,
  },
  // Ergonomic Chairs
  {
    id: "31",
    name: "UltraComfort Ergonomic Chair",
    description:
      "Ergonomic chair with advanced lumbar support for long hours of work.",
    price: 249.99,
    image: "https://images.unsplash.com/photo-1681418659069-eef28d44aeab?w=500",
    category: "Ergonomic Chair",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "32",
    name: "Executive Ergonomic Chair",
    description:
      "High-back chair designed for executives with comfort and style in mind.",
    price: 299.99,
    image:
      "https://plus.unsplash.com/premium_photo-1661542322251-db8b9bdf8e30?w=500",
    category: "Ergonomic Chair",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "33",
    name: "Mesh Ergonomic Chair",
    description:
      "Breathable mesh chair providing excellent posture support and flexibility.",
    price: 199.99,
    image: "https://images.unsplash.com/photo-1594235048794-fae8583a5af5?w=500",
    category: "Ergonomic Chair",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "34",
    name: "Ergo Deluxe Chair",
    description:
      "Premium ergonomic chair with multiple adjustable features for personalized comfort.",
    price: 329.99,
    image:
      "https://plus.unsplash.com/premium_photo-1681558314227-33174756677d?w=500",
    category: "Ergonomic Chair",
    rating: 4.9,
    inStock: true,
  },
  // Mouses
  {
    id: "35",
    name: "Precision Wireless Mouse",
    description:
      "High-precision wireless mouse with customizable buttons for productivity.",
    price: 49.99,
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=500",
    category: "Mouse",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "36",
    name: "Ergo Wireless Mouse",
    description:
      "Ergonomically designed mouse for comfortable use during long work sessions.",
    price: 39.99,
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500",
    category: "Mouse",
    rating: 4.4,
    inStock: true,
  },
  {
    id: "37",
    name: "Gaming Wireless Mouse",
    description:
      "Responsive and accurate gaming mouse with adjustable DPI settings.",
    price: 59.99,
    image: "https://images.unsplash.com/photo-1563297007-0686b7003af7?w=500",
    category: "Mouse",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "38",
    name: "Budget Wired Mouse",
    description:
      "Reliable wired mouse offering simplicity and precision at an affordable price.",
    price: 19.99,
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=500",
    category: "Mouse",
    rating: 4.2,
    inStock: true,
  },
  // Monitors
  {
    id: "39",
    name: "UltraWide Monitor",
    description:
      "Immersive ultrawide display for enhanced productivity and multimedia experiences.",
    price: 399.99,
    image: "https://images.unsplash.com/photo-1666771410003-8437c4781d49?w=500",
    category: "Monitor",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "40",
    name: "4K Gaming Monitor",
    description:
      "High resolution gaming monitor with fast refresh rates and vibrant colors.",
    price: 499.99,
    image: "https://images.unsplash.com/photo-1585362028211-dee1aba5fdd3?w=500",
    category: "Monitor",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "41",
    name: "Curved Office Monitor",
    description:
      "Ergonomically curved monitor designed to reduce eye strain during long work hours.",
    price: 329.99,
    image: "https://images.unsplash.com/photo-1547119957-637f8679db1e?w=500",
    category: "Monitor",
    rating: 4.4,
    inStock: true,
  },
  {
    id: "42",
    name: "Professional Color Monitor",
    description:
      "Monitors designed for designers and photographers requiring accurate color reproduction.",
    price: 599.99,
    image: "https://images.unsplash.com/photo-1586210579191-33b45e38fa2c?w=500",
    category: "Monitor",
    rating: 4.9,
    inStock: true,
  },
  // Keyboards
  {
    id: "43",
    name: "Mechanical Gaming Keyboard",
    description:
      "RGB backlit mechanical keyboard with fast response times for gaming enthusiasts.",
    price: 89.99,
    image: "https://images.unsplash.com/photo-1595225476474-87563907a212?w=500",
    category: "Keyboard",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "44",
    name: "Ergonomic Keyboard",
    description:
      "Keyboard designed to reduce strain and provide a comfortable typing experience.",
    price: 69.99,
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=500",
    category: "Keyboard",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "45",
    name: "Wireless Compact Keyboard",
    description:
      "Portable, wireless keyboard perfect for on-the-go productivity.",
    price: 49.99,
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=500",
    category: "Keyboard",
    rating: 4.3,
    inStock: true,
  },
  {
    id: "46",
    name: "Backlit Office Keyboard",
    description:
      "Quiet and comfortable keyboard with subtle backlighting for office use.",
    price: 59.99,
    image: "https://images.unsplash.com/photo-1601445638532-3c6f6c3aa1d6?w=500",
    category: "Keyboard",
    rating: 4.4,
    inStock: true,
  },
  // Office Accessories
  {
    id: "47",
    name: "Ergo Desk Lamp",
    description:
      "Adjustable LED desk lamp to reduce eye strain during extended working hours.",
    price: 79.99,
    image: "https://images.unsplash.com/photo-1619608135352-868e8313e121?w=500",
    category: "Office Accessory",
    rating: 4.4,
    inStock: true,
  },
  {
    id: "48",
    name: "Wireless Charging Pad",
    description: "Fast wireless charger for smartphones and wearable devices.",
    price: 29.99,
    image: "https://images.unsplash.com/photo-1622445275463-afa2ab738c34?w=500",
    category: "Office Accessory",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "49",
    name: "Bluetooth Speaker",
    description:
      "Portable Bluetooth speaker with excellent sound quality for your workspace.",
    price: 59.99,
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500",
    category: "Office Accessory",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "50",
    name: "Desktop Webcam",
    description: "High-definition webcam for video conferencing and streaming.",
    price: 89.99,
    image: "https://images.unsplash.com/photo-1623949556303-b0d17d198863?w=500",
    category: "Office Accessory",
    rating: 4.4,
    inStock: true,
  },
  // Additional Accessories & Other
  {
    id: "51",
    name: "Noise Cancelling Headphones",
    description:
      "Over-ear headphones with active noise cancellation for immersive sound.",
    price: 149.99,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500",
    category: "Audio",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "52",
    name: "Portable SSD 1TB",
    description:
      "High-speed portable SSD for fast data transfer and reliable storage.",
    price: 129.99,
    image: "https://images.unsplash.com/photo-1662601326685-fe26f65cdb17?w=500",
    category: "Storage",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "53",
    name: "Smartwatch Series 5",
    description:
      "Feature-packed smartwatch with fitness tracking and notifications.",
    price: 199.99,
    image: "https://images.unsplash.com/photo-1544117519-31a4b719223d?w=500",
    category: "Wearable",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "54",
    name: "Portable Power Bank",
    description:
      "High capacity power bank to keep your devices charged on the go.",
    price: 39.99,
    image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=500",
    category: "Accessories",
    rating: 4.3,
    inStock: true,
  },
  {
    id: "55",
    name: "Ergonomic Foot Rest",
    description:
      "Designed to relieve foot strain and improve posture during long hours at your desk.",
    price: 24.99,
    image:
      "https://plus.unsplash.com/premium_photo-1681426775958-4e7ba85a77f1?w=500",
    category: "Office Accessory",
    rating: 4.2,
    inStock: true,
  },
  {
    id: "56",
    name: "Laptop Cooling Pad",
    description:
      "Enhance your laptop's performance by preventing overheating with this cooling pad.",
    price: 34.99,
    image: "https://images.unsplash.com/photo-1619953942547-233eab5a70d6?w=500",
    category: "Laptop Accessory",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "57",
    name: "Wireless Presenter",
    description:
      "Convenient wireless presenter ideal for meetings and presentations.",
    price: 29.99,
    image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=500",
    category: "Office Accessory",
    rating: 4.3,
    inStock: true,
  },
  {
    id: "58",
    name: "Digital Drawing Tablet",
    description:
      "Ideal for digital artists; includes a stylus and customizable shortcuts.",
    price: 89.99,
    image: "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=500",
    category: "Creative Tools",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "59",
    name: "VR Headset",
    description:
      "Step into the world of virtual reality with this immersive VR headset.",
    price: 299.99,
    image: "https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?w=500",
    category: "Gaming",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "60",
    name: "Multi-Port USB Hub",
    description:
      "Expand your connectivity with a multi-port USB hub for all your devices.",
    price: 39.99,
    image: "https://images.unsplash.com/photo-1625961332771-3f40b0e2bdcf?w=500",
    category: "Accessories",
    rating: 4.4,
    inStock: true,
  },
];
